name: "SWM GitHub Actions Basic"

on: push

env:
  PRESET_VALUE: 'This is PRESET_VALUE'

jobs:
  first-job:
    name: "First Job"

    runs-on: ubuntu-latest

    steps:
      - name: "Set output value"
        id: first
        shell: bash
        run: |
          var_1="This is the value 1 in the step 1"

          echo "::set-output name=first_value::$var_1"

      - name: "Output output value"
        shell: pwsh
        run: |
          echo ${{ steps.first.outputs.first_value}}
