name: "SWM GitHub Actions Basic"

on: push

env:
  PRESET_VALUE: 'This is PRESET_VALUE'

jobs:
  first-job:
    name: "First Job"

    runs-on: ubuntu-latest

    steps:
      - name: "Set enviorment variable 1"
        shell: bash
        run: |
          var_1='This is the value 1 in the step 1'

          echo "STEPSET_VALUE_1=$var_1" >> $GITHUB_ENV

      - name: "say Hello world 12"
        shell: pwsh
        env:
          STEP_LEVEL_12: 'this value comes from the step level 12'
        run: |
          var_2='This is the value 2 in the step 2"

          echo "STEPSET_VALUE_2=$var_2" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: 'CHeck environment variables'
        shell: bash
        run: |
          echo "preset value: ${{env.PRESET_VALUE}}"
          echo "stepset value 1: ${{env.PRESET_VALUE_1}}"
          echo "stepset value 2: ${{env.PRESET_VALUE_2}}"